name: 'CoPe | communications & photography'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65951
title: 'CoPe | communications & photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9dcd72'
    - '#7e7e7e'
    - '#2e2e2e'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.5645455690100789
  rhythmicContrast: 0.75
purpose: []
