typography_spectrum: 0.7616488
color:
  saturation: 0.5625
  brandStrength: 0.1875
  rhythmicContrast: 0.75
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9dcd72'
    - '#7e7e7e'
    - '#2e2e2e'
  lightness: 0.6875
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dd2c32b1-ae8f-4981-a28f-6570d8d59a32.jpg
name: CoPe | communications & photography
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3d7dcc4c-fe75-4935-bd30-8a86d4cd8383.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
purpose: []
