name: 'CoPe | communications & photography'
favicon: null
layout_spectrum: 0.166915284935385
typography_spectrum: 0.7846461876761168
title: creative writing. inspiring images. affective media.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9dcd72'
    - '#000000'
    - '#afafaf'
    - '#5f5f5f'
  brandStrength: 0.75
  lightness: 0.6471003014594316
  saturation: 0.5645455690100789
  rhythmicContrast: 0.1053251528646797
purpose: []
